"""Banque SUPPLÉMENTAIRE de piques sarcastiques et d'avis passagers
(Kevin, 09/10/2026 : « augmente la liste de tes commentaires sarcastiques
adaptés aux circonstances, et les avis des passagers aussi, pour grossir la
base et ne pas avoir tout le temps les mêmes »).

Source UNIQUE pour les deux programmes : perce_neige_sim.py ajoute ces
listes aux siennes ; la PWA reçoit la même chose par
godot_project/scripts/pn_quips_extra.gd, GÉNÉRÉ par tools_piques.py (ne pas
le modifier à la main : relancer « python3 tools_piques.py »).

Piques : (fr, en). Avis : (qui avec drapeau, VO, fr, en) ; VO vide ou égale
au français quand le passager est francophone.
Circonstances nouvelles : choc LENT au butoir (< 3 m/s) et choc VIOLENT
(> 8 m/s), en plus des listes générales.
"""

CRASH = [
    ("Le butoir était là depuis 1993. Vous l'avez découvert aujourd'hui.",
     "The buffer stop has been there since 1993. You found it today."),
    ("Les skieurs voulaient la neige. Ils ont eu le béton.",
     "The skiers wanted snow. They got concrete."),
    ("Bravo : vous avez transformé 3,5 km de tunnel en piste de bowling.",
     "Well done: you turned 3.5 km of tunnel into a bowling alley."),
    ("L'assurance a appelé. Elle aussi voudrait descendre.",
     "The insurer called. They'd like to get off too."),
    ("Arrêt « au repère » : le repère est désormais dans le mur.",
     "Stopped 'on the mark': the mark is now inside the wall."),
    ("La machinerie a tout donné. Vous, vous avez tout pris.",
     "The drive gave everything. You took everything."),
    ("Le régulateur proposait 100 %. Vous avez entendu « illimité ».",
     "The governor offered 100 %. You heard 'unlimited'."),
    ("Félicitations : premier funiculaire à atterrir.",
     "Congratulations: first funicular ever to land."),
    ("Le glacier de la Grande Motte a reculé de 50 m. Pas assez pour vous.",
     "The Grande Motte glacier retreated 50 m. Not enough for you."),
    ("Le moniteur ESF en cabine note : « chasse-neige non maîtrisé ».",
     "The ski instructor on board notes: 'snowplough not mastered'."),
    ("Ce n'était pas un exercice. Enfin, maintenant, si.",
     "That was not a drill. Well, now it is."),
    ("Vos passagers ont gagné un forfait. Pour l'ostéopathe.",
     "Your passengers won a pass. For the osteopath."),
    ("Le câble a tenu. Les nerfs des passagers, moins.",
     "The cable held. The passengers' nerves, less so."),
    ("Ralentir avant la gare : une tradition que vous bousculez.",
     "Slowing down before the station: a tradition you're shaking up."),
    ("Le chef d'exploitation vous attend. Avec un café. Très serré.",
     "The operations manager is waiting. With a coffee. Very strong."),
    ("Votre note de conduite rejoint l'altitude de départ : 2 111… sous zéro.",
     "Your driving grade matches the start altitude: 2,111… below zero."),
    ("Vous aviez 3 474 m pour freiner. Vous avez gardé les 3 derniers cm.",
     "You had 3,474 m to brake. You kept the last 3 cm."),
    ("Le butoir hydraulique a fait son travail. C'était le seul.",
     "The hydraulic buffer did its job. It was the only one."),
    ("Prochaine fois, essayez le bouton marqué « frein ». Il est rouge.",
     "Next time, try the button marked 'brake'. It's the red one."),
    ("Les pompiers de Tignes vous ajoutent à leurs favoris.",
     "Tignes fire brigade has added you to their favourites."),
]

# choc au butoir à faible vitesse (< 3 m/s) : presque réussi
CRASH_LENT = [
    ("Si près du but. Littéralement : vous êtes DEDANS.",
     "So close. Literally: you're IN it."),
    ("À 2 m/s, ce n'est plus un accident, c'est un câlin appuyé.",
     "At 2 m/s it's not a crash, it's a firm hug."),
    ("Le butoir a à peine bougé. Votre fierté, beaucoup plus.",
     "The buffer barely moved. Your pride moved a lot more."),
    ("Un mètre de plus de freinage et c'était un 5 étoiles. Dommage.",
     "One more metre of braking and it was five stars. Shame."),
    ("Accostage version pétrolier : lent, lourd, mais au mauvais endroit.",
     "Tanker-style docking: slow, heavy, and in the wrong place."),
    ("Les passagers debout ont fait un petit pas en avant. Tous ensemble.",
     "The standing passengers all took one small step forward. Together."),
    ("Presque un arrêt parfait. « Presque » : le mot le plus cher du métier.",
     "Almost a perfect stop. 'Almost': the costliest word in the trade."),
    ("Le butoir a dit « aïe ». Poliment.",
     "The buffer said 'ouch'. Politely."),
]

# choc au butoir à grande vitesse (> 8 m/s)
CRASH_VIOLENT = [
    ("À cette vitesse, la gare haute s'appelle maintenant la gare basse.",
     "At that speed, the top station is now the bottom station."),
    ("Les sismographes de Grenoble vous saluent.",
     "The Grenoble seismographs send their regards."),
    ("Plein régime jusqu'au butoir : audacieux. Définitif, aussi.",
     "Full power into the buffer: bold. Also final."),
    ("Vous n'avez pas freiné tard. Vous n'avez pas freiné du tout.",
     "You didn't brake late. You didn't brake at all."),
    ("La rame a gagné quelques mètres de tunnel. Creusés par elle-même.",
     "The train gained a few metres of tunnel. Dug by itself."),
    ("Record de vitesse au butoir homologué. Par le légiste.",
     "Buffer-stop speed record confirmed. By the coroner."),
    ("Von Roll a calculé ce butoir pour l'improbable. Vous l'avez rendu certain.",
     "Von Roll sized that buffer for the improbable. You made it certain."),
    ("Les 334 passagers sont arrivés en avance. Tous au même endroit.",
     "All 334 passengers arrived early. All in the same spot."),
]

DERAIL = [
    ("L'aiguillage Abt n'a pas de pièce mobile. Vous, si : trop.",
     "The Abt switch has no moving parts. You did: too many."),
    ("Mi-parcours, mi-tunnel, mi-rail : l'évitement en trois morceaux.",
     "Half-way, half-tunnel, half-rail: the passing loop in three pieces."),
    ("Les roues à double boudin vous ont fait confiance. Erreur.",
     "The double-flanged wheels trusted you. Mistake."),
    ("Vous avez trouvé la troisième voie. Elle n'existe pas.",
     "You found the third track. It doesn't exist."),
    ("Croiser l'autre rame, c'est À CÔTÉ. Pas à travers la paroi.",
     "Passing the other car means BESIDE it. Not through the wall."),
    ("La courbe de l'évitement est douce. C'est vous qui ne l'étiez pas.",
     "The passing-loop curve is gentle. You weren't."),
    ("Déraillement à 1 000 m sous terre : le spéléo vous remercie.",
     "Derailing 1,000 m underground: the caving club thanks you."),
    ("Le profil disait « ralentir ». Vous avez lu « décoller ».",
     "The profile said 'slow down'. You read 'take off'."),
    ("Les ingénieurs ont mis 18 mois à poser ce rail. Vous, 0,4 s à le quitter.",
     "Engineers took 18 months to lay that rail. You took 0.4 s to leave it."),
    ("Nouvelle attraction : le Perce-Roche.",
     "New attraction: the Rock-Piercer."),
]

CABIN = [
    ("Le croisement a lieu À L'ÉVITEMENT. Pas n'importe où.",
     "Trains pass at the PASSING LOOP. Not just anywhere."),
    ("Vous avez trouvé l'autre rame. Elle se cachait pourtant bien.",
     "You found the other car. It was hiding so well, too."),
    ("Face à face à 30 km/h : les passagers ont fait connaissance.",
     "Head-on at 30 km/h: the passengers got acquainted."),
    ("Un seul câble, deux rames : ça devait finir en contrepoids, pas en carambolage.",
     "One cable, two cars: it was meant to be a counterweight, not a pile-up."),
    ("Le conducteur de la rame 2 dépose un préavis de grève.",
     "Car 2's driver has filed a strike notice."),
    ("Le tunnel est à voie unique. Votre jugement aussi.",
     "The tunnel is single-track. So is your judgement."),
    ("Collision avec la seule autre rame à 3 km à la ronde. Statistiquement fort.",
     "Collision with the only other car for 3 km. Statistically impressive."),
    ("La rame 2 était arrêtée, freinée, signalée. Vous étiez… motivé.",
     "Car 2 was stopped, braked, signalled. You were… motivated."),
]

REVERSE = [
    ("Demi-tour en plein tunnel : les skieurs vous trouvent indécis.",
     "U-turn mid-tunnel: the skiers find you indecisive."),
    ("Monter, descendre, remonter… c'est un funiculaire, pas un yo-yo.",
     "Up, down, up again… it's a funicular, not a yo-yo."),
    ("Le glacier attendra. Visiblement, il a l'habitude.",
     "The glacier will wait. Clearly it's used to it."),
    ("Changement d'avis ? Les 334 passagers aussi, sur vous.",
     "Change of mind? The 334 passengers changed theirs too — about you."),
    ("Le câble s'enroule dans l'autre sens. Vos passagers aussi, d'agacement.",
     "The cable winds the other way. So do your passengers, in annoyance."),
    ("Inverser le sens, c'est légal. L'enthousiasme, moins.",
     "Reversing is legal. The enthusiasm, less so."),
    ("Bonne nouvelle : vous connaissez déjà le trajet.",
     "Good news: you already know the way."),
    ("Marche arrière : la vue sur le tunnel est identique, rassurez-vous.",
     "Reverse gear: the tunnel view is exactly the same, don't worry."),
]

DOORS_OPEN = [
    ("Portes ouvertes en marche : le courant d'air est offert par la maison.",
     "Doors open on the move: the draught is on the house."),
    ("Le tunnel fait 3,9 m de diamètre. Les portes ouvertes, un peu plus.",
     "The tunnel is 3.9 m wide. With the doors open, slightly more."),
    ("Un snowboardeur vient de tenter la sortie latérale. Note : 2/10.",
     "A snowboarder just attempted a side exit. Score: 2/10."),
    ("Les verrouillages de portes existent. Ils sont juste vexés.",
     "Door interlocks exist. They're just offended."),
    ("Un bâton de ski vient de partir seul vers Val Claret.",
     "A ski pole just left on its own for Val Claret."),
    ("Climatisation naturelle : −10 °C, vent de face, gratuit.",
     "Natural air conditioning: −10 °C, headwind, free of charge."),
    ("Le bruit que vous entendez, c'est le règlement qui claque la porte. L'autre.",
     "That noise is the rulebook slamming a door. The other one."),
    ("Rouler portes ouvertes : idéal pour perdre des passagers et des procès.",
     "Driving with doors open: ideal for losing passengers and lawsuits."),
]

REVIEWS = {
    "great": [
        ("🇮🇹 Giulia, Milano",
         "Che classe! Partenza dolce, arrivo perfetto. Il mio espresso non si è mosso.",
         "Quelle classe ! Départ doux, arrivée parfaite. Mon espresso n'a pas bougé.",
         "Such class! Gentle start, perfect arrival. My espresso didn't move."),
        ("🇪🇸 Javier, Madrid",
         "¡Increíble! Ni me di cuenta de que habíamos parado. Conductor de diez.",
         "Incroyable ! Je ne me suis même pas rendu compte qu'on s'était arrêtés. Conducteur parfait.",
         "Incredible! I didn't even notice we'd stopped. Ten-out-of-ten driver."),
        ("🇬🇧 Oliver, Leeds",
         "Spot on. Smoother than my tea, and I make a very good tea.",
         "Impeccable. Plus doux que mon thé, et je fais un très bon thé.",
         "Spot on. Smoother than my tea, and I make a very good tea."),
        ("🇺🇸 Madison, Denver",
         "Okay this was AMAZING. Like an elevator that loves you. Five stars!!",
         "Bon, c'était GÉNIAL. Comme un ascenseur qui vous aime. Cinq étoiles !!",
         "Okay this was AMAZING. Like an elevator that loves you. Five stars!!"),
        ("🇳🇱 Sanne, Utrecht",
         "Heel netjes. Precies op tijd en precies op de streep. Gezellig ook.",
         "Très propre. Pile à l'heure et pile sur la ligne. Convivial en plus.",
         "Very neat. Right on time and right on the line. Cosy too."),
        ("🇳🇴 Ingrid, Tromsø",
         "Rolig og presist. Som en god fjelltur, bare raskere og varmere.",
         "Calme et précis. Comme une belle randonnée en montagne, en plus rapide et plus chaud.",
         "Calm and precise. Like a good mountain hike, only faster and warmer."),
        ("🇸🇪 Erik, Göteborg",
         "Lagom. Precis lagom. Det är det finaste jag kan säga.",
         "Lagom. Exactement lagom. C'est le plus beau compliment que je connaisse.",
         "Lagom. Exactly lagom. It's the nicest thing I can say."),
        ("🇩🇰 Mette, Aarhus",
         "Hyggeligt og helt uden ryk. Chaufføren fortjener en kanelsnegl.",
         "Agréable et sans le moindre à-coup. Le conducteur mérite une brioche à la cannelle.",
         "Pleasant and not a single jolt. The driver deserves a cinnamon bun."),
        ("🇵🇱 Kasia, Kraków",
         "Super! Zatrzymał się co do centymetra. Dzieci nawet nie zauważyły.",
         "Super ! Arrêt au centimètre près. Les enfants n'ont même rien remarqué.",
         "Great! Stopped to the centimetre. The kids didn't even notice."),
        ("🇧🇷 Rafael, São Paulo",
         "Que viagem gostosa! Suave do começo ao fim. Nota mil pro motorista.",
         "Quel voyage agréable ! Doux du début à la fin. Note maximale pour le conducteur.",
         "What a lovely ride! Smooth from start to finish. Top marks to the driver."),
        ("🇵🇹 Inês, Porto",
         "Perfeito. Nem uma gota de café entornada. Voltarei com a família.",
         "Parfait. Pas une goutte de café renversée. Je reviendrai avec la famille.",
         "Perfect. Not a drop of coffee spilled. I'll come back with the family."),
        ("🇰🇷 Jiwoo, Busan",
         "완벽해요! 출발도 도착도 정말 부드러웠어요. 기사님 최고!",
         "Parfait ! Le départ comme l'arrivée, d'une douceur incroyable. Le conducteur est le meilleur !",
         "Perfect! Both departure and arrival were so smooth. Best driver!"),
        ("🇨🇳 Wei, Chengdu",
         "非常平稳，准时到站。司机技术一流，值得五星。",
         "Très stable, arrivée à l'heure. Le conducteur est de premier ordre, il mérite cinq étoiles.",
         "Very steady, on time. First-class driver, worth five stars."),
        ("🇨🇿 Tomáš, Brno",
         "Výborně. Plynulá jízda, přesné zastavení. Jako dobře natočené pivo.",
         "Excellent. Conduite fluide, arrêt précis. Comme une bière bien tirée.",
         "Excellent. Smooth ride, precise stop. Like a well-poured beer."),
        ("🇫🇮 Aino, Tampere",
         "Hiljainen, sujuva ja täsmällinen. Melkein kuin sauna: rentouttava.",
         "Silencieux, fluide et précis. Presque comme un sauna : relaxant.",
         "Quiet, smooth and precise. Almost like a sauna: relaxing."),
        ("🇧🇪 Lucas, Namur",
         "",
         "Une fois, c'était parfait. Même ma grand-mère debout n'a pas tenu la barre.",
         "Honestly, it was perfect. Even my standing grandma didn't hold the rail."),
        ("🇨🇦 Émilie, Québec",
         "",
         "Wow, c'est doux en tabarnouche ! Le chauffeur a des mains de pâtissier.",
         "Wow, that was super smooth! The driver has the hands of a pastry chef."),
        ("🇫🇷 Margaux, Lyon",
         "",
         "Pas un à-coup, pile au quai, la porte en face de moi. Je n'ai rien à redire, et ça m'agace.",
         "Not a jolt, right on the platform, door right in front of me. Nothing to complain about, and it annoys me."),
        ("🇦🇹 Lukas, Innsbruck",
         "Leiwand! So sanft wie ein Sessellift bei Windstille.",
         "Génial ! Aussi doux qu'un télésiège par temps calme.",
         "Brilliant! As gentle as a chairlift on a still day."),
        ("🇮🇪 Siobhán, Galway",
         "Grand job altogether. I'd buy the driver a pint, maybe two.",
         "Du beau travail. J'offrirais une pinte au conducteur, peut-être deux.",
         "Grand job altogether. I'd buy the driver a pint, maybe two."),
    ],
    "rough": [
        ("🇮🇹 Marco, Torino",
         "Mamma mia, che frenata! Il cappuccino ora è sul giubbotto del vicino.",
         "Mamma mia, quel freinage ! Le cappuccino est maintenant sur la veste du voisin.",
         "Mamma mia, what braking! The cappuccino is now on my neighbour's jacket."),
        ("🇪🇸 Lucía, Sevilla",
         "Llegamos, sí. Pero con el estómago en la garganta.",
         "On est arrivés, oui. Mais avec l'estomac dans la gorge.",
         "We got there, yes. But with my stomach in my throat."),
        ("🇬🇧 Harriet, Bath",
         "Rather bumpy, I'm afraid. My scone has opinions about it.",
         "Plutôt cahoteux, j'en ai peur. Mon scone a un avis là-dessus.",
         "Rather bumpy, I'm afraid. My scone has opinions about it."),
        ("🇺🇸 Tyler, Austin",
         "Bro hit the brakes like he saw a moose. There are no moose in a tunnel.",
         "Le gars a freiné comme s'il avait vu un élan. Il n'y a pas d'élan dans un tunnel.",
         "Bro hit the brakes like he saw a moose. There are no moose in a tunnel."),
        ("🇳🇱 Daan, Rotterdam",
         "Beetje schokkerig. Mijn fiets op de pont reed soepeler.",
         "Un peu saccadé. Mon vélo sur le bac roulait plus en douceur.",
         "A bit jerky. My bike on the ferry rode smoother."),
        ("🇩🇪 Petra, Köln",
         "Abfahrt ruppig, Ankunft holprig, dazwischen okay. Drei Sterne, aus Höflichkeit.",
         "Départ brusque, arrivée cahoteuse, entre les deux ça allait. Trois étoiles, par politesse.",
         "Rough start, bumpy arrival, fine in between. Three stars, out of politeness."),
        ("🇨🇭 Reto, Bern",
         "Nid schlächt, aber dr Halt isch e chli z'fescht gsi.",
         "Pas mal, mais l'arrêt était un peu trop sec.",
         "Not bad, but the stop was a bit too firm."),
        ("🇸🇪 Linnea, Uppsala",
         "Det gick, men jag höll i stången med båda händerna hela vägen.",
         "Ça allait, mais j'ai tenu la barre à deux mains tout le trajet.",
         "It was fine, but I held the rail with both hands the whole way."),
        ("🇵🇱 Piotr, Gdańsk",
         "Dojechaliśmy. Moje narty wylądowały u sąsiada.",
         "On est arrivés. Mes skis ont atterri chez le voisin.",
         "We arrived. My skis landed on the next guy."),
        ("🇧🇷 Camila, Rio",
         "Chegamos, mas parecia montanha-russa sem a parte divertida.",
         "On est arrivés, mais on aurait dit des montagnes russes sans la partie amusante.",
         "We made it, but it felt like a roller coaster without the fun part."),
        ("🇯🇵 Haruto, Sapporo",
         "到着は少し急でした。でも景色は…トンネルでした。",
         "L'arrivée était un peu brusque. Mais le paysage… c'était un tunnel.",
         "The arrival was a little abrupt. But the scenery… was a tunnel."),
        ("🇰🇷 Minji, Seoul",
         "출발이 너무 갑작스러웠어요. 커피를 다 쏟았어요.",
         "Le départ était trop brusque. J'ai renversé tout mon café.",
         "The departure was too sudden. I spilled all my coffee."),
        ("🇨🇿 Jana, Praha",
         "Trochu drkotavé. Ale aspoň jsme nezůstali v tunelu.",
         "Un peu cahoteux. Mais au moins on n'est pas restés dans le tunnel.",
         "A bit bumpy. But at least we didn't stay in the tunnel."),
        ("🇳🇴 Sindre, Bergen",
         "Bremsene ble brukt med stor entusiasme. Kanskje litt for stor.",
         "Les freins ont été utilisés avec beaucoup d'enthousiasme. Peut-être un peu trop.",
         "The brakes were used with great enthusiasm. Perhaps too great."),
        ("🇧🇪 Sarah, Liège",
         "",
         "On est arrivés, mais ma fille a demandé si c'était un manège. Ce n'était pas un compliment.",
         "We got there, but my daughter asked if it was a ride. It wasn't a compliment."),
        ("🇫🇷 Bernard, Annecy",
         "",
         "Quarante ans que je monte au glacier. Jamais un arrêt aussi… expressif.",
         "Forty years going up to the glacier. Never such an… expressive stop."),
        ("🇨🇦 Maxime, Montréal",
         "",
         "Ça brassait pas mal. J'ai cru que c'était le métro de Montréal en heure de pointe.",
         "It was pretty shaky. I thought it was the Montreal metro at rush hour."),
        ("🇦🇺 Liam, Perth",
         "Bit of a rough landing, mate. Still beats a kangaroo strike.",
         "Atterrissage un peu rude, mon pote. Ça reste mieux qu'un kangourou dans le pare-chocs.",
         "Bit of a rough landing, mate. Still beats a kangaroo strike."),
        ("🇩🇰 Rasmus, Odense",
         "Det var okay, men mine ski og jeg er ikke længere venner.",
         "C'était correct, mais mes skis et moi ne sommes plus amis.",
         "It was okay, but my skis and I are no longer friends."),
        ("🇦🇹 Anna, Salzburg",
         "Mei, a bissl ruckelig war's schon. Aber angekommen san ma.",
         "Bon, c'était un peu secoué quand même. Mais on est arrivés.",
         "Well, it was a bit shaky. But we got there."),
    ],
    "disaster": [
        ("🇮🇹 Federica, Bologna",
         "Mai più. Ho visto la mia vita passare, e anche quella del mio vicino.",
         "Plus jamais. J'ai vu ma vie défiler, et celle de mon voisin aussi.",
         "Never again. I saw my life flash by, and my neighbour's too."),
        ("🇪🇸 Pablo, Bilbao",
         "¿Esto es un funicular o una prueba de choque? Una estrella porque no hay cero.",
         "C'est un funiculaire ou un crash-test ? Une étoile parce que zéro n'existe pas.",
         "Is this a funicular or a crash test? One star because zero isn't an option."),
        ("🇬🇧 Nigel, Croydon",
         "Absolutely dreadful. I shall be writing to someone. Possibly everyone.",
         "Absolument épouvantable. Je vais écrire à quelqu'un. Peut-être à tout le monde.",
         "Absolutely dreadful. I shall be writing to someone. Possibly everyone."),
        ("🇺🇸 Brittany, Ohio",
         "My lawyer has entered the chat. One star.",
         "Mon avocat vient d'entrer dans la conversation. Une étoile.",
         "My lawyer has entered the chat. One star."),
        ("🇩🇪 Jürgen, Hamburg",
         "Unfassbar. Ich bin Ingenieur. Ich habe GERECHNET. Das war nicht vorgesehen.",
         "Incroyable. Je suis ingénieur. J'ai CALCULÉ. Ce n'était pas prévu.",
         "Unbelievable. I'm an engineer. I CALCULATED. That was not in the plan."),
        ("🇨🇭 Ursula, Basel",
         "Schrecklich. Mini Uhr isch stoh blibe. Und mis Härz fascht au.",
         "Horrible. Ma montre s'est arrêtée. Et mon cœur aussi, presque.",
         "Terrible. My watch stopped. And my heart nearly did too."),
        ("🇳🇱 Joost, Eindhoven",
         "Dit was geen rit, dit was een botsproef. Ik wil mijn skipas terug.",
         "Ce n'était pas un trajet, c'était un crash-test. Je veux qu'on me rembourse mon forfait.",
         "That wasn't a ride, it was a crash test. I want my lift pass refunded."),
        ("🇸🇪 Oskar, Malmö",
         "Jag har åkt Kebnekaise i storm. Det här var värre.",
         "J'ai fait le Kebnekaise dans la tempête. C'était pire.",
         "I've climbed Kebnekaise in a storm. This was worse."),
        ("🇳🇴 Kari, Oslo",
         "Jeg tar heller trappene neste gang. Alle 3 491 meterne.",
         "La prochaine fois je prends l'escalier. Les 3 491 mètres.",
         "Next time I'll take the stairs. All 3,491 metres of them."),
        ("🇵🇱 Agnieszka, Wrocław",
         "Koszmar. Moje dzieci teraz chcą jeździć tylko wyciągiem orczykowym.",
         "Cauchemar. Mes enfants ne veulent plus prendre que le téléski.",
         "Nightmare. My kids now only want to ride the T-bar."),
        ("🇧🇷 Thiago, Recife",
         "Pior experiência da minha vida, e eu já andei de ônibus no Carnaval.",
         "Pire expérience de ma vie, et j'ai déjà pris le bus pendant le Carnaval.",
         "Worst experience of my life, and I've ridden a bus during Carnival."),
        ("🇵🇹 João, Lisboa",
         "O elétrico 28 é uma carícia comparado com isto.",
         "Le tram 28 de Lisbonne est une caresse à côté de ça.",
         "Lisbon's tram 28 is a caress compared to this."),
        ("🇯🇵 Sakura, Kyoto",
         "信じられません。日本ではこんなことは絶対に起きません。",
         "Incroyable. Au Japon, ça n'arriverait jamais.",
         "Unbelievable. This would never happen in Japan."),
        ("🇰🇷 Seojun, Incheon",
         "최악이에요. 스키보다 이 열차가 더 위험해요.",
         "Le pire. Ce train est plus dangereux que le ski.",
         "The worst. This train is more dangerous than skiing."),
        ("🇨🇳 Li, Shanghai",
         "太可怕了！我的滑雪板飞到了前面的车厢。",
         "Terrifiant ! Mon snowboard s'est envolé jusque dans la voiture de devant.",
         "Terrifying! My snowboard flew into the car in front."),
        ("🇨🇿 Pavel, Ostrava",
         "Hrůza. I tramvaj v Ostravě brzdí jemněji.",
         "Horreur. Même le tram d'Ostrava freine plus doucement.",
         "Horror. Even the Ostrava tram brakes more gently."),
        ("🇫🇮 Mikko, Oulu",
         "Perkele. Ei muuta sanottavaa.",
         "Perkele. Rien d'autre à ajouter.",
         "Perkele. Nothing more to say."),
        ("🇫🇷 Chantal, Bourg-Saint-Maurice",
         "",
         "J'ai perdu une chaussure, mon bonnet et ma foi en l'humanité. Une étoile, pour le tunnel qui a tenu.",
         "I lost a shoe, my hat and my faith in humanity. One star, for the tunnel that held."),
        ("🇧🇪 Jean-Marc, Charleroi",
         "",
         "C'est la première fois que je vois un funiculaire faire un tonneau. Enfin presque.",
         "First time I've seen a funicular do a barrel roll. Well, almost."),
        ("🇨🇦 Sébastien, Sherbrooke",
         "",
         "Mon père est déneigeur depuis 30 ans, il n'a jamais rien frappé aussi fort.",
         "My dad's been a snowplough driver for 30 years and never hit anything that hard."),
    ],
}

# --- Mode skieur (Kevin, 09/10/2026 : « si je fais du hors-piste, ou que je
# loupe le funiculaire, ou que j'évacue… avec parcimonie, sinon on se
# lasse »). Tirées au plus une fois toutes les quelques minutes. ----------

SKIEUR_HORS_PISTE = [
    ("Hors-piste : la poudreuse est belle, le pisteur beaucoup moins content.",
     "Off-piste: the powder is lovely, the ski patrol much less so."),
    ("Vous avez quitté la piste. La piste ne s'en remettra pas.",
     "You've left the piste. The piste will never recover."),
    ("Les balises jaunes et noires, c'est décoratif, bien sûr.",
     "The yellow-and-black markers are just decorative, of course."),
    ("Itinéraire original. Le secours en montagne adore l'originalité.",
     "Original route. Mountain rescue loves originality."),
    ("Pas de piste ici. Juste vous, la pente, et un léger doute.",
     "No piste here. Just you, the slope and a slight doubt."),
    ("Ce n'est pas un raccourci si personne ne le connaît.",
     "It's not a shortcut if nobody knows it."),
    ("Le DVA est allumé ? Non ? Le DVA n'est jamais allumé.",
     "Avalanche beacon on? No? It's never on."),
    ("Bel itinéraire « bis ». Bis, comme « bis repetita : on vous cherche ».",
     "Nice alternative route. Alternative, as in 'we're out looking for you'."),
]

SKIEUR_RATE = [
    ("Le funiculaire est parti. Sans vous. Il n'attend personne, même pas vous.",
     "The funicular has left. Without you. It waits for no one, not even you."),
    ("Prochain départ dans quelques minutes. Le temps de méditer sur la ponctualité.",
     "Next departure in a few minutes. Time to reflect on punctuality."),
    ("Raté. 334 places, et aucune pour vous.",
     "Missed it. 334 seats, none of them yours."),
    ("Les portes se ferment toutes seules. Vous, vous traînez tout seul.",
     "The doors close by themselves. You dawdle by yourself."),
    ("Vous regardez partir la rame comme on regarde partir un ferry : avec regret.",
     "Watching the train leave like watching a ferry leave: with regret."),
    ("Le buzzer, c'était pour vous. Ah, trop tard.",
     "The buzzer was for you. Ah, too late."),
]

SKIEUR_EVACUATION = [
    ("Évacuation : marchez calmement, ne courez pas, et surtout ne racontez pas ça au comptoir.",
     "Evacuation: walk calmly, don't run, and above all don't tell it at the bar."),
    ("Bienvenue dans la galerie de secours. Peu de touristes la connaissent. Veinard.",
     "Welcome to the escape gallery. Few tourists ever see it. Lucky you."),
    ("Le tunnel à pied : 3,5 km d'ambiance garantie, sans la musique.",
     "The tunnel on foot: 3.5 km of guaranteed atmosphere, minus the music."),
    ("Vous évacuez en chaussures de ski. Les pompiers prennent des notes.",
     "Evacuating in ski boots. The firefighters are taking notes."),
    ("Issue de secours ouverte : vous venez d'entrer dans le cercle très fermé des évacués.",
     "Emergency exit open: you've just joined the very exclusive evacuees' club."),
]

SKIEUR_VOIE = [
    ("Marcher sur la voie d'un funiculaire : déconseillé par 10 dentistes sur 10.",
     "Walking on a funicular track: not recommended by 10 out of 10 dentists."),
    ("La rame vous attend. Elle n'a pas le choix, et elle le vit mal.",
     "The train is waiting for you. It has no choice, and it resents it."),
    ("Promenade dans le tunnel : la vue est la même partout, ne cherchez pas.",
     "A stroll through the tunnel: the view is the same everywhere, don't bother."),
]
